inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'

Rails:
  Enabled: true

Metrics/ClassLength:
  Max: 130
  Exclude:
    - 'lib/browse_everything/v1/driver/google_drive.rb'
    - 'lib/browse_everything/provider/google_drive.rb'
    - 'lib/browse_everything/upload.rb'
Layout/LineLength:
  Max: 400
  Exclude:
    - 'spec/lib/browse_everything/v1/driver/box_spec.rb'
    - 'spec/lib/browse_everything/v1/driver/dropbox_spec.rb'

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*'
    - 'swagger/spec/**/*'
Metrics/MethodLength:
  Exclude:
    - 'lib/browse_everything/v1/driver/google_drive.rb'
    - 'lib/browse_everything/provider/google_drive.rb'

Lint/UselessAssignment:
  Exclude:
    - 'app/controllers/browse_everything/authorizations_controller.rb'
    - 'app/controllers/browse_everything/bytestreams_controller.rb'
    - 'app/controllers/browse_everything/containers_controller.rb'
    - 'app/controllers/browse_everything/sessions_controller.rb'
    - 'app/controllers/browse_everything/uploads_controller.rb'

RSpec/NestedGroups:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/javascripts/**/*'

RSpec/LeadingSubject:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/EmptyExampleGroup:
  Exclude:
    - 'swagger/spec/integration/authorizations_spec.rb'
    - 'swagger/spec/integration/bytestreams_spec.rb'
    - 'swagger/spec/integration/containers_spec.rb'
    - 'swagger/spec/integration/providers_spec.rb'
    - 'swagger/spec/integration/sessions_spec.rb'
    - 'swagger/spec/integration/uploads_spec.rb'
    - 'spec/controllers/browse_everything/sessions_controller_spec.rb'

Style/NumericLiterals:
  MinDigits: 7

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Naming/FileName:
  Exclude:
    - 'browse-everything.gemspec'
    - 'Gemfile'
    - 'lib/browse-everything.rb'

Naming/MemoizedInstanceVariableName:
  Exclude:
    - 'lib/browse_everything/upload.rb'

Style/MixinUsage:
  Exclude:
    - 'spec/lib/browse_everything/v1/driver/s3_spec.rb'
    - 'spec/lib/browse_everything/v1/driver/google_drive_spec.rb'
    - 'spec/lib/browse_everything/v1/driver/file_system_spec.rb'
    - 'spec/lib/browse_everything/v1/driver/dropbox_spec.rb'
    - 'spec/lib/browse_everything/v1/driver/box_spec.rb'
    - 'spec/lib/browse_everything/v1/driver/base_spec.rb'
    - 'spec/lib/browse_everything/browser_spec.rb'
    - 'spec/services/browser_factory_spec.rb'
    - 'spec/helper/browse_everything_controller_helper_spec.rb'

Bundler/DuplicatedGem:
  Exclude:
    - 'Gemfile'

RSpec/EmptyExampleGroup:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/MixinUsage:
  Enabled: false
Layout/LineLength:
  Enabled: false
