language: ruby
dist: trusty
sudo: required
addons:
  chrome: stable
cache:
  bundler: true

before_install:
  - gem update --system # https://docs.travis-ci.com/user/languages/ruby/#Upgrading-RubyGems
  - gem install bundler

rvm:
  - 2.4.3

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  matrix:
    - "RAILS_VERSION=5.1.4"
    - "RAILS_VERSION=5.0.6"
