---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@0

jobs:
  build:
    parameters:
      ruby_version:
        type: string
      rails_version:
        type: string
      bundler_version:
        type: string
        default: 2.1.4
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
    steps:
      - samvera/cached_checkout

      - samvera/bundle_for_gem:
          bundler_version: << parameters.bundler_version >>
          ruby_version: << parameters.ruby_version >>
          project: 'browse-everything'

      - samvera/engine_cart_generate:
          cache_key: v2-internal-test-app-{{ checksum "browse-everything.gemspec" }}-{{ checksum "spec/test_app_templates/lib/generators/test_app_generator.rb" }}-{{ checksum "lib/generators/browse_everything/install_generator.rb" }}-{{ checksum "lib/generators/browse_everything/config_generator.rb" }}--<< parameters.rails_version >>-<< parameters.ruby_version >>

      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: 'browse-everything'

      - samvera/rubocop

      - run:
          name: Install Karma for JavaScript and functional tests
          command: sudo npm install -g karma karma-jasmine karma-chrome-launcher

      - run:
          name: Run rspec in parallel
          command: |
            mkdir /tmp/test-results
            bundle exec rspec --exclude-pattern "swagger/**/*_spec.rb" $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
  ci:
    jobs:
      - build:
          name: "ruby3-2_rails7-2"
          ruby_version: 3.2.5
          rails_version: 7.2.1
