---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@1.0

jobs:
  build:
    parameters:
      ruby_version:
        type: string
      rails_version:
        type: string
      bundler_version:
        type: string
        default: 2.1.4
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
    steps:
      - samvera/cached_checkout

      - run:
          name: Check for a branch named 'master'
          command: |
            git fetch --all --quiet --prune --prune-tags
            if [[ -n "$(git branch --all --list master */master)" ]]; then
              echo "A branch named 'master' was found. Please remove it."
              echo "$(git branch --all --list master */master)"
            fi
            [[ -z "$(git branch --all --list master */master)" ]]

      - samvera/bundle:
          bundler_version: << parameters.bundler_version >>
          ruby_version: << parameters.ruby_version >>

      - samvera/engine_cart_generate:
          cache_key: v1-internal-test-app-{{ checksum "browse-everything.gemspec" }}-{{ checksum "Gemfile" }}-{{ checksum "spec/test_app_templates/lib/generators/test_app_generator.rb" }}-{{ checksum "lib/generators/browse_everything/install_generator.rb" }}-{{ checksum "lib/generators/browse_everything/config_generator.rb" }}--<< parameters.rails_version >>-<< parameters.ruby_version >>

      - run:
         name: Update sprockets to fix version incompatibilities between internal test app and initial bundle install
         command: bundle update sprockets

      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: 'browse-everything'

      - samvera/rubocop

      - run:
          name: Install Karma for JavaScript and functional tests
          command: sudo npm install -g karma karma-jasmine karma-chrome-launcher

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      - build:
          name: "ruby2-7_rails6-0"
          ruby_version: 2.7.5
          rails_version: 6.0.4.7
      - build:
          name: "ruby2-6_rails6-0"
          ruby_version: 2.6.9
          rails_version: 6.0.4.7

      - build:
          name: "ruby2-7_rails5-2"
          ruby_version: 2.7.5
          rails_version: 5.2.7
      - build:
          name: "ruby2-6_rails5-2"
          ruby_version: 2.6.9
          rails_version: 5.2.7

      - build:
          name: "ruby2-7_rails5-1"
          ruby_version: 2.7.5
          rails_version: 5.1.7
      - build:
          name: "ruby2-6_rails5-1"
          ruby_version: 2.6.9
          rails_version: 5.1.7

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build:
          name: "ruby2-7_rails6-0"
          ruby_version: 2.7.5
          rails_version: 6.0.4.7
      - build:
          name: "ruby2-6_rails6-0"
          ruby_version: 2.6.9
          rails_version: 6.0.4.7

      - build:
          name: "ruby2-7_rails5-2"
          ruby_version: 2.7.5
          rails_version: 5.2.7
      - build:
          name: "ruby2-6_rails5-2"
          ruby_version: 2.6.9
          rails_version: 5.2.7

      - build:
          name: "ruby2-7_rails5-1"
          ruby_version: 2.7.5
          rails_version: 5.1.7
      - build:
          name: "ruby2-6_rails5-1"
          ruby_version: 2.6.9
          rails_version: 5.1.7

