---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@1.0
  browser-tools: circleci/browser-tools@1.1

jobs:
  build:
    parameters:
      ruby_version:
        type: string
      rails_version:
        type: string
      bundler_version:
        type: string
        default: 2.1.4
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
    steps:
      - browser-tools/install-chrome

      - samvera/cached_checkout

      - run:
          name: Check for a branch named 'master'
          command: |
            git fetch --all --quiet --prune --prune-tags
            if [[ -n "$(git branch --all --list master */master)" ]]; then
              echo "A branch named 'master' was found. Please remove it."
              echo "$(git branch --all --list master */master)"
            fi
            [[ -z "$(git branch --all --list master */master)" ]]

      - samvera/bundle:
          bundler_version: << parameters.bundler_version >>
          ruby_version: << parameters.ruby_version >>

      - samvera/rubocop

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      - build:
          name: "ruby3-2_rails7-0"
          ruby_version: 3.2.0
          rails_version: 7.0.3
      - build:
          name: "ruby3-1_rails7-0"
          ruby_version: 3.1.2
          rails_version: 7.0.3

      - build:
          name: "ruby3-1_rails6-1"
          ruby_version: 3.1.2
          rails_version: 6.1.6
      - build:
          name: "ruby3-0_rails6-1"
          ruby_version: 3.0.3
          rails_version: 6.1.6

      - build:
          name: "ruby3-0_rails6-0"
          ruby_version: 3.0.3
          rails_version: 6.0.4.7
      - build:
          name: "ruby2-7_rails6-0"
          ruby_version: 2.7.5
          rails_version: 6.0.4.7
      - build:
          name: "ruby2-6_rails6-0"
          ruby_version: 2.6.9
          rails_version: 6.0.4.7

      - build:
          name: "ruby2-7_rails5-2"
          ruby_version: 2.7.5
          rails_version: 5.2.7
      - build:
          name: "ruby2-6_rails5-2"
          ruby_version: 2.6.9
          rails_version: 5.2.7

      - build:
          name: "ruby2-7_rails5-1"
          ruby_version: 2.7.5
          rails_version: 5.1.7
      - build:
          name: "ruby2-6_rails5-1"
          ruby_version: 2.6.9
          rails_version: 5.1.7

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build:
          name: "ruby3-1_rails7-0"
          ruby_version: 3.1.2
          rails_version: 7.0.3

      - build:
          name: "ruby3-1_rails6-1"
          ruby_version: 3.1.2
          rails_version: 6.1.6
      - build:
          name: "ruby3-0_rails6-1"
          ruby_version: 3.0.3
          rails_version: 6.1.6

      - build:
          name: "ruby3-0_rails6-0"
          ruby_version: 3.0.3
          rails_version: 6.0.4.7
      - build:
          name: "ruby2-7_rails6-0"
          ruby_version: 2.7.5
          rails_version: 6.0.4.7
      - build:
          name: "ruby2-6_rails6-0"
          ruby_version: 2.6.9
          rails_version: 6.0.4.7

      - build:
          name: "ruby2-7_rails5-2"
          ruby_version: 2.7.5
          rails_version: 5.2.7
      - build:
          name: "ruby2-6_rails5-2"
          ruby_version: 2.6.9
          rails_version: 5.2.7

      - build:
          name: "ruby2-7_rails5-1"
          ruby_version: 2.7.5
          rails_version: 5.1.7
      - build:
          name: "ruby2-6_rails5-1"
          ruby_version: 2.6.9
          rails_version: 5.1.7

