---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@1.0
  browser-tools: circleci/browser-tools@1.1

jobs:
  build:
    parameters:
      ruby_version:
        type: string
      rails_version:
        type: string
      bundler_version:
        type: string
        default: 2.5.21
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
    steps:
      - browser-tools/install-chrome

      - samvera/cached_checkout

      - run:
          name: Check for a branch named 'master'
          command: |
            git fetch --all --quiet --prune --prune-tags
            if [[ -n "$(git branch --all --list master */master)" ]]; then
              echo "A branch named 'master' was found. Please remove it."
              echo "$(git branch --all --list master */master)"
            fi
            [[ -z "$(git branch --all --list master */master)" ]]

      - samvera/bundle:
          bundler_version: << parameters.bundler_version >>
          ruby_version: << parameters.ruby_version >>

      - samvera/rubocop

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      - build:
          name: "ruby3-3_rails7-2"
          ruby_version: 3.3.5
          rails_version: 7.2.1
      - build:
          name: "ruby3-2_rails7-1"
          ruby_version: 3.2.5
          rails_version: 7.1.4
      - build:
          name: "ruby3-2_rails7-0"
          ruby_version: 3.2.5
          rails_version: 7.0.8.4
      - build:
          name: "ruby3-1_rails7-0"
          ruby_version: 3.1.6
          rails_version: 7.0.8.4
      - build:
          name: "ruby3-1_rails6-1"
          ruby_version: 3.1.6
          rails_version: 6.1.7.8

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build:
          name: "ruby3-3_rails7-2"
          ruby_version: 3.3.3
          rails_version: "7.2.0"
      - build:
          name: "ruby3-2_rails7-1"
          ruby_version: 3.2.0
          rails_version: 7.1.1
      - build:
          name: "ruby3-2_rails7-0"
          ruby_version: 3.2.0
          rails_version: 7.0.4
      - build:
          name: "ruby3-1_rails7-0"
          ruby_version: 3.1.2
          rails_version: 7.0.4
      - build:
          name: "ruby3-1_rails6-1"
          ruby_version: 3.1.2
          rails_version: 6.1.6

